# 1. Database Connection (Points to a local file named dating.db)
spring.datasource.url=jdbc:sqlite:dating.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# 2. Hibernate SQL Dialect Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect

# 2.5
# Force Hibernate to use the exact physical column names defined in your @Column annotations
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


# 3. Schema Strategy (Set to 'none' because EF Core already created the tables)
spring.jpa.hibernate.ddl-auto=none

# 4. Debugging Tool (Prints generated SQL strings directly to the VS Code terminal)
spring.jpa.show-sql=true
